# GitHub Action Workflow enforcing our code style.

name: Lint, Build & Deploy

# Trigger the workflow on both push (to the main repository)
# and pull requests (against the main repository, but from any repo).
on:
  push:
    paths:
      - '*.py'
  pull_request:
    paths:
      - '*.py'

# Brand new concurrency setting! This ensures that not more than one run can be triggered for the same commit.
# It is useful for pull requests coming from the main repository since both triggers will match.

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        python_version: [3.7, 3.8, 3.9]
        os: [ubuntu-18.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    env:
      # Set an environment variable to select pip's cache directory for us to actually cache between runs.
      PIP_CACHE_DIR: /tmp/pip-cache-dir

    steps:
      # Checks out the repository in the current folder.
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}
      
      - name: Install dependencies
        run: |
          pip install wheel flake8

      - name: Install poetry
        uses: abatilo/actions-poetry@v2.0.0
      
      - name: Install poetry dependencies
        run: |
          poetry install

      - name: Run flake8
        run: |
          flake8 --format='::error file=%(path)s,line=%(row)d,col=%(col)d::[flake8] %(code)s: %(text)s'

